### ISSUE TITLE
Exception while setting up cluster

### ISSUE THREAD

**Issue by sanjeevkanabargi** [sakserv/hadoop-mini-clusters#31] opened 2017-03-30 08:16 UTC
I am getting **"java.lang.IllegalArgumentException: The value of property bind.address must not be null"** while using hdfsmilicluster. can anyone please help me to resolve this issue ?

Code snippet : 

```java
static HdfsLocalCluster hdfsLocalCluster = null;

@Before
public void setup() throws Exception{
         System.setProperty("HADOOP_HOME", "D:\\myProject\\hadoopFiles\\hadoop-mini-clusters-master\\" +
				"windows_libs\\2.5.0.0\\");
        Configuration conf = new Configuration();

	hdfsLocalCluster = new HdfsLocalCluster.Builder()
        .setHdfsNamenodePort(12345)
        .setHdfsNamenodeHttpPort(8080)
        .setHdfsTempDir("embedded_hdfs")
        .setHdfsNumDatanodes(1)
        .setHdfsEnablePermissions(false)
        .setHdfsFormat(true)
        .setHdfsEnableRunningUserAsProxyUser(true)
        .setHdfsConfig(conf)
        .build();
        try{
		hdfsLocalCluster.start();
	}catch(Exception ex){
			System.out.println("Excption :");
			ex.printStackTrace();
			throw new Exception(ex.getMessage());
	}
}
```

Exception : 

    java.lang.IllegalArgumentException: The value of property bind.address must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1142)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1123)
	at org.apache.hadoop.http.HttpServer2.initializeWebServer(HttpServer2.java:449)
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:398)
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:110)
	at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:324)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:155)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:834)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:692)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:898)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:877)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1603)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1151)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1026)
	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:819)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:479)
	at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:438)
	at com.github.sakserv.minicluster.impl.HdfsLocalCluster.start(HdfsLocalCluster.java:179)
	at com.symantec.adl.sdk.trident.utils.SetupTestClusters.setupHDFSLocalCluster(SetupTestClusters.java:113)
	at test.java.TestReadHDFS.setup(TestReadHDFS.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by sakserv** [comment] 2017-04-03 21:55
@sanjeevkanabargi sorry for the delayed response. 

This isn't one I've encountered before, but it appears you are running on Windows, which may be why I'm not seeing it.

In looking at the Namenode and HTTPServer2 code, it seems "bind.host" in the HTTPServer should be set to the HTTP port used by the NameNode. 

Can you try to explicitly add the property "dfs.namenode.http-bind-host" to your configuration object and set it to "0.0.0.0:8080" or "<ip of your workstation>:8080"?

Let me know if that helped. Thanks!

**Comment by sanjeevkanabargi** [comment] 2017-04-14 13:17
@sakserv  Thank you for response, I will check with the configuration you mentioned and reply you soon.

**Comment by sakserv** [comment] 2017-04-30 16:47
@sanjeevkanabargi - I'm going to close this for now as I've been unable to reproduce the issue. Please reopen this issue when you have more details. Thanks!

**Closed by sakserv** 2017-04-30 16:47 UTC

**Comment by biaoma-ty** [comment] 2021-04-13 09:26
I can reproduce this exception in version 3.3.0 on a specific machine, but not sure what's the difference of the ethernet card settings between this machine and others, since other machine can not reproduce this exception.

Manually set the dfs.namenode.http-bind-host config is not working in my case.

Is there any config could I change to find out the reason for this exception?

**Comment by biaoma-ty** [comment] 2021-04-13 09:28
Code snippet:
```java
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hdfs.MiniDFSCluster;

/**
 * @author lewinma@tencent.com
 * @date 2021/4/12 18:08
 */
public class MiniClusterTest {

    public static void main(String[] args) throws IOException {
        String basePath = "test";
        File baseDir = Files.createTempDirectory(basePath).toFile().getAbsoluteFile();
        Configuration conf = new Configuration();
        conf.set(MiniDFSCluster.HDFS_MINIDFS_BASEDIR, baseDir.getAbsolutePath());
        MiniDFSCluster.Builder builder = new MiniDFSCluster.Builder(conf);
        MiniDFSCluster hdfsCluster = builder.build();
        hdfsCluster.shutdown(true, true);
        hdfsCluster.close();
    }

}

```
Here is the full stack exception:
```java
2021-04-13 17:22:07,186 INFO  [main] hdfs.MiniDFSCluster (MiniDFSCluster.java:<init>(509)) - starting cluster: numNameNodes=1, numDataNodes=1
2021-04-13 17:22:07,596 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(60)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-04-13 17:22:07,691 INFO  [main] namenode.NameNode (NameNode.java:format(1245)) - Formatting using clusterid: testClusterID
2021-04-13 17:22:07,707 INFO  [main] namenode.FSEditLog (FSEditLog.java:newInstance(229)) - Edit logging is async:true
2021-04-13 17:22:07,731 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(814)) - KeyProvider: null
2021-04-13 17:22:07,732 INFO  [main] namenode.FSNamesystem (FSNamesystemLock.java:<init>(130)) - fsLock is fair: true
2021-04-13 17:22:07,733 INFO  [main] namenode.FSNamesystem (FSNamesystemLock.java:<init>(148)) - Detailed lock hold time metrics enabled: false
2021-04-13 17:22:07,790 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(847)) - fsOwner                = devops (auth:SIMPLE)
2021-04-13 17:22:07,790 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(848)) - supergroup             = supergroup
2021-04-13 17:22:07,791 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(849)) - isPermissionEnabled    = true
2021-04-13 17:22:07,791 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(850)) - isStoragePolicyEnabled = true
2021-04-13 17:22:07,791 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(861)) - HA Enabled: false
2021-04-13 17:22:07,842 INFO  [main] common.Util (Util.java:isDiskStatsEnabled(395)) - dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling
2021-04-13 17:22:07,846 INFO  [main] Configuration.deprecation (Configuration.java:logDeprecation(1418)) - hadoop.configured.node.mapping is deprecated. Instead, use net.topology.configured.node.mapping
2021-04-13 17:22:07,846 INFO  [main] blockmanagement.DatanodeManager (DatanodeManager.java:<init>(306)) - dfs.block.invalidate.limit: configured=1000, counted=60, effected=1000
2021-04-13 17:22:07,846 INFO  [main] blockmanagement.DatanodeManager (DatanodeManager.java:<init>(314)) - dfs.namenode.datanode.registration.ip-hostname-check=true
2021-04-13 17:22:07,852 INFO  [main] blockmanagement.BlockManager (InvalidateBlocks.java:printBlockDeletionTime(77)) - dfs.namenode.startup.delay.block.deletion.sec is set to 000:00:00:00.000
2021-04-13 17:22:07,853 INFO  [main] blockmanagement.BlockManager (InvalidateBlocks.java:printBlockDeletionTime(83)) - The block deletion will start around 2021 4月 13 17:22:07
2021-04-13 17:22:07,854 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map BlocksMap
2021-04-13 17:22:07,854 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2021-04-13 17:22:07,857 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 2.0% max memory 3.8 GB = 78.6 MB
2021-04-13 17:22:07,857 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^23 = 8388608 entries
2021-04-13 17:22:07,886 INFO  [main] blockmanagement.BlockManager (BlockManager.java:createSPSManager(5424)) - Storage policy satisfier is disabled
2021-04-13 17:22:07,886 INFO  [main] blockmanagement.BlockManager (BlockManager.java:createBlockTokenSecretManager(641)) - dfs.block.access.token.enable = false
2021-04-13 17:22:07,892 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(160)) - dfs.namenode.safemode.threshold-pct = 0.999
2021-04-13 17:22:07,892 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(161)) - dfs.namenode.safemode.min.datanodes = 0
2021-04-13 17:22:07,892 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(163)) - dfs.namenode.safemode.extension = 0
2021-04-13 17:22:07,893 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(627)) - defaultReplication         = 1
2021-04-13 17:22:07,893 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(628)) - maxReplication             = 512
2021-04-13 17:22:07,893 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(629)) - minReplication             = 1
2021-04-13 17:22:07,893 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(630)) - maxReplicationStreams      = 2
2021-04-13 17:22:07,893 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(631)) - redundancyRecheckInterval  = 3000ms
2021-04-13 17:22:07,894 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(632)) - encryptDataTransfer        = false
2021-04-13 17:22:07,894 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(633)) - maxNumBlocksToLog          = 1000
2021-04-13 17:22:07,911 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - GLOBAL serial map: bits=29 maxEntries=536870911
2021-04-13 17:22:07,912 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - USER serial map: bits=24 maxEntries=16777215
2021-04-13 17:22:07,912 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - GROUP serial map: bits=24 maxEntries=16777215
2021-04-13 17:22:07,912 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - XATTR serial map: bits=24 maxEntries=16777215
2021-04-13 17:22:07,921 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map INodeMap
2021-04-13 17:22:07,921 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2021-04-13 17:22:07,921 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 1.0% max memory 3.8 GB = 39.3 MB
2021-04-13 17:22:07,921 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^22 = 4194304 entries
2021-04-13 17:22:07,932 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(333)) - ACLs enabled? true
2021-04-13 17:22:07,932 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(337)) - POSIX ACL inheritance enabled? true
2021-04-13 17:22:07,932 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(341)) - XAttrs enabled? true
2021-04-13 17:22:07,932 INFO  [main] namenode.NameNode (FSDirectory.java:<init>(401)) - Caching file names occurring more than 10 times
2021-04-13 17:22:07,937 INFO  [main] snapshot.SnapshotManager (SnapshotManager.java:<init>(124)) - Loaded config captureOpenFiles: false, skipCaptureAccessTimeOnlyChange: false, snapshotDiffAllowSnapRootDescendant: true, maxSnapshotLimit: 65536
2021-04-13 17:22:07,938 INFO  [main] snapshot.SnapshotManager (DirectoryDiffListFactory.java:init(43)) - SkipList is disabled
2021-04-13 17:22:07,942 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map cachedBlocks
2021-04-13 17:22:07,942 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2021-04-13 17:22:07,943 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 0.25% max memory 3.8 GB = 9.8 MB
2021-04-13 17:22:07,943 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^20 = 1048576 entries
2021-04-13 17:22:07,954 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(76)) - NNTop conf: dfs.namenode.top.window.num.buckets = 10
2021-04-13 17:22:07,955 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(78)) - NNTop conf: dfs.namenode.top.num.users = 10
2021-04-13 17:22:07,955 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(80)) - NNTop conf: dfs.namenode.top.windows.minutes = 1,5,25
2021-04-13 17:22:07,958 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:initRetryCache(1080)) - Retry cache on namenode is enabled
2021-04-13 17:22:07,958 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:initRetryCache(1088)) - Retry cache will use 0.03 of total heap and retry cache entry expiry time is 600000 millis
2021-04-13 17:22:07,960 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map NameNodeRetryCache
2021-04-13 17:22:07,960 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2021-04-13 17:22:07,960 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 0.029999999329447746% max memory 3.8 GB = 1.2 MB
2021-04-13 17:22:07,961 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^17 = 131072 entries
2021-04-13 17:22:07,988 INFO  [main] namenode.FSImage (FSImage.java:format(185)) - Allocated new BlockPoolId: BP-544338713-127.0.0.1-1618305727976
2021-04-13 17:22:08,012 INFO  [main] common.Storage (NNStorage.java:format(595)) - Storage directory /tmp/pulsar7651193457003172555/name-0-1 has been successfully formatted.
2021-04-13 17:22:08,024 INFO  [main] common.Storage (NNStorage.java:format(595)) - Storage directory /tmp/pulsar7651193457003172555/name-0-2 has been successfully formatted.
2021-04-13 17:22:08,057 INFO  [FSImageSaver for /tmp/pulsar7651193457003172555/name-0-2 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(716)) - Saving image file /tmp/pulsar7651193457003172555/name-0-2/current/fsimage.ckpt_0000000000000000000 using no compression
2021-04-13 17:22:08,057 INFO  [FSImageSaver for /tmp/pulsar7651193457003172555/name-0-1 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(716)) - Saving image file /tmp/pulsar7651193457003172555/name-0-1/current/fsimage.ckpt_0000000000000000000 using no compression
2021-04-13 17:22:08,175 INFO  [FSImageSaver for /tmp/pulsar7651193457003172555/name-0-2 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(720)) - Image file /tmp/pulsar7651193457003172555/name-0-2/current/fsimage.ckpt_0000000000000000000 of size 401 bytes saved in 0 seconds .
2021-04-13 17:22:08,175 INFO  [FSImageSaver for /tmp/pulsar7651193457003172555/name-0-1 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(720)) - Image file /tmp/pulsar7651193457003172555/name-0-1/current/fsimage.ckpt_0000000000000000000 of size 401 bytes saved in 0 seconds .
2021-04-13 17:22:08,195 INFO  [main] namenode.NNStorageRetentionManager (NNStorageRetentionManager.java:getImageTxIdToRetain(203)) - Going to retain 1 images with txid >= 0
2021-04-13 17:22:08,198 INFO  [main] namenode.NameNode (NameNode.java:createNameNode(1696)) - createNameNode []
2021-04-13 17:22:08,243 WARN  [main] impl.MetricsConfig (MetricsConfig.java:loadFirst(134)) - Cannot locate configuration: tried hadoop-metrics2-namenode.properties,hadoop-metrics2.properties
2021-04-13 17:22:08,356 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:startTimer(374)) - Scheduled Metric snapshot period at 10 second(s).
2021-04-13 17:22:08,356 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:start(191)) - NameNode metrics system started
2021-04-13 17:22:08,377 INFO  [main] namenode.NameNodeUtils (NameNodeUtils.java:getClientNamenodeAddress(79)) - fs.defaultFS is hdfs://127.0.0.1:8080
2021-04-13 17:22:08,377 INFO  [main] namenode.NameNode (NameNode.java:<init>(1005)) - Clients should use 127.0.0.1:8080 to access this namenode/service.
2021-04-13 17:22:08,431 INFO  [org.apache.hadoop.util.JvmPauseMonitor$Monitor@649f2009] util.JvmPauseMonitor (JvmPauseMonitor.java:run(188)) - Starting JVM pause monitor
2021-04-13 17:22:08,440 INFO  [main] hdfs.DFSUtil (DFSUtil.java:httpServerTemplateForNNAndJN(1669)) - Filter initializers set : org.apache.hadoop.http.lib.StaticUserWebFilter,org.apache.hadoop.hdfs.web.AuthFilterInitializer
2021-04-13 17:22:08,444 INFO  [main] hdfs.DFSUtil (DFSUtil.java:httpServerTemplateForNNAndJN(1691)) - Starting Web-server for hdfs at: http://VM_66_43_centos:0
2021-04-13 17:22:08,455 INFO  [main] util.log (Log.java:initialized(169)) - Logging initialized @1842ms to org.eclipse.jetty.util.log.Slf4jLog
2021-04-13 17:22:08,542 INFO  [main] server.AuthenticationFilter (AuthenticationFilter.java:constructSecretProvider(240)) - Unable to initialize FileSignerSecretProvider, falling back to use random secrets.
2021-04-13 17:22:08,546 INFO  [main] http.HttpRequestLog (HttpRequestLog.java:getRequestLog(82)) - Http request log for http.requests.namenode is not defined
2021-04-13 17:22:08,551 INFO  [main] http.HttpServer2 (HttpServer2.java:addGlobalFilter(1059)) - Added global filter 'safety' (class=org.apache.hadoop.http.HttpServer2$QuotingInputFilter)
2021-04-13 17:22:08,554 INFO  [main] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdown(2067)) - Shutting down the Mini HDFS Cluster
Exception in thread "main" java.lang.IllegalArgumentException: The value of property bind.address must not be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1380)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1361)
        at org.apache.hadoop.http.HttpServer2.initializeWebServer(HttpServer2.java:677)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:635)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:123)
        at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:459)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:152)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:946)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:757)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:1014)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:987)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1756)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1332)
        at org.apache.hadoop.hdfs.MiniDFSCluster.configureNameService(MiniDFSCluster.java:1101)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:974)
        at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:906)
        at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:534)
        at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:493)
        at io.github.lewin.minihdfs.MiniClusterTest.main(MiniClusterTest.java:21)

```
